language: java
sudo: false

jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 - echo "package com.kumpel.dom.bot.controller.bdcontroller;
          public interface ConnectionInterface {

            String HN = "";
            String DB = "";
            String URL = "jdbc:mysql://" + HN + "/" + DB;
            String UN = "";
            String PW = "";
            String DR = "com.mysql.jdbc.Driver";
        }" > src/main/java/com/kumpel/dom/bot/controller/bdcontroller/ConnectionInterface.java

after_success:
  - bash <(curl -s https://codecov.io/bash) -t token <(curl -s https://codecov.io/bash)