language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk8

script: ./gradlew build jacocoTestReport
sudo: required

env:
  matrix:
  - TERM=dumb

before_install:
  - chmod +x gradlew
  - echo "package com.kumpel.dom.bot.model.bdcontroller;
          public interface ConnectionInterface {
            String HN = new String();
            String DB = new String();
            String URL = new String();
            String UN = new String();
            String PW = new String();
            String DR = new String();

        }" > src/main/java/com/kumpel/dom/bot/controller/bdcontroller/ConnectionInterface.java

  - echo "package com.kumpel.dom.bot.view;

          public interface Token {

              String TOKEN = new String();
          }" > src/main/java/com/kumpel/dom/bot/view/Token.java

after_success:
  - ./gradlew jacocoRootReport coveralls
  - bash <(curl -s https://codecov.io/bash) -t token <(curl -s https://codecov.io/bash)