language: java
sudo: false

jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 - echo "package com.kumpel.dom.bot.controller.bdcontroller;
          public interface ConnectionInterface {
            String HN = new String();
            String DB = new String();
            String URL = new String();
            String UN = new String();
            String PW = new String();
            String DR = new String();

        }" > src/main/java/com/kumpel/dom/bot/controller/bdcontroller/ConnectionInterface.java

after_success:
  - bash <(curl -s https://codecov.io/bash) -t token <(curl -s https://codecov.io/bash)